version: "3.5"

services:
  db_mongo:
    image: mongo:3
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "1234"
  app:
    build: ./src/
    command: bash -c "npm run dev"
    environment:
      NODE_ENV: "local"
    # volumes:
    #   - ./src/:/usr/src/app
    depends_on:
      - db_mongo
    ports:
      - 3000:3000
      - 9229:9229
